name: oval-core-tools
base: core22
version: '0.10'
summary: This snap provides basic tools for CVE Reporting on Ubuntu Core.
description: |
  This snap provides basic tools for OVAL-based CVE Reporting on Ubuntu Core.

grade: devel # must be 'stable' to release into candidate/stable channels

# Note -- this might not actually work, but is being updated to help test
# validation set semantics. The last known working revisions for arm64 are
# r23 & r25!
confinement: strict

architectures:
  - build-on: [ 'amd64' ]
    build-for: [ 'amd64' ]
  - build-on: [ 'arm64' ]
    build-for: [ 'arm64' ]
  - build-on: [ 'armhf' ]
    build-for: [ 'armhf' ]

apps:
  cvereport:
    command: cvereport.sh
    environment:
        LD_LIBRARY_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/android:$LD_LIBRARY_PATH

parts:
  oval-tools:
    plugin: python
    source: ./oval-tools
    python-packages: [pyyaml]
  report:
    plugin: dump
    source: ./report
    stage-packages:
      - android-sdk-libsparse-utils
      - bzip2
      - curl
      - file
      - jq
      - kpartx
      - libopenscap8
      - wget
      - xmlstarlet
    stage:
      - -usr/lib/*/libicuio.so.*
      - -usr/lib/*/libicutest.so.*
      - -usr/lib/*/libicutu.so*
      - -usr/lib/*/libicui18n.so*
      - -usr/lib/*/libopenscap_sce.so.*

layout:
  /usr/share/misc/magic.mgc:
    symlink: $SNAP/usr/share/misc/magic.mgc
  /usr/share/openscap/schemas:
    symlink: $SNAP/usr/share/openscap/schemas
  /usr/share/openscap/xsl:
    symlink: $SNAP/usr/share/openscap/xsl
  # required due to oval_probe_eval chdir() logic
  /usr/lib/$CRAFT_ARCH_TRIPLET/openscap:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/openscap
