name: oval-core-tools
base: core22
version: '0.1sed'
summary: This snap provides basic tools for CVE Reporting on Ubuntu Core.
description: |
  This snap provides basic tools for OVAL-based CVE Reporting on Ubuntu Core.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  cvereport:
    command: cvereport.sh
  scan:
    command: bin/snap_manifest.py

parts:
  snap-manifests:
    plugin: python
    source: ./snap-manifests
    python-packages: [pyyaml]
  report:
    plugin: dump
    source: ./report
    stage-packages:
      - bzip2
      - curl
      - jq
      - libopenscap8
      - wget
      - xmlstarlet
    stage:
      - -usr/lib/*/libicuio.so.*
      - -usr/lib/*/libicutest.so.*
      - -usr/lib/*/libicutu.so*
      - -usr/lib/*/libicui18n.so*
      - -usr/lib/*/libopenscap_sce.so.*

layout:
  /usr/share/openscap/schemas:
    symlink: $SNAP/usr/share/openscap/schemas
  # required due to oval_probe_eval chdir() logic
  /usr/lib/x86_64-linux-gnu/openscap:
    symlink: $SNAP/usr/lib/x86_64-linux-gnu/openscap
